# Generated by Django 5.0 on 2023-12-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_id_customer_details_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
