# Generated by Django 5.0 on 2023-12-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_details_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='consignment_no',
            field=models.CharField(unique=True),
        ),
    ]
