# Generated by Django 5.0 on 2023-12-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_details_consignment_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
