# Generated by Django 5.0 on 2023-12-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_details_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='payment_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
