# Generated by Django 5.0 on 2023-12-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_details_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(unique=True)),
                ('product_wholesale_rate', models.CharField(unique=True)),
                ('total_sold', models.IntegerField()),
            ],
        ),
    ]
