# Generated by Django 5.0 on 2023-12-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='total_sold',
            field=models.IntegerField(null=True),
        ),
    ]
