# Generated by Django 5.0 on 2023-12-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_product_details_total_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='product_wholesale_rate',
            field=models.CharField(),
        ),
    ]
