# Generated by Django 5.0 on 2023-12-27 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_product_details_product_wholesale_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='product_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.product_details'),
        ),
    ]
