# Generated by Django 5.0 on 2023-12-27 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customer_details_product_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('payment_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('paid_on', models.DateField()),
                ('rr_amount', models.IntegerField()),
                ('invoice_amount', models.IntegerField()),
                ('ibft_fee', models.IntegerField()),
                ('net_payable', models.IntegerField()),
                ('instrument_mode', models.CharField(max_length=255)),
                ('instrument_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer_details',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='customer_details',
            name='payment_fk',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.paymentdetails'),
        ),
    ]
